# Generated by Django 2.0.4 on 2018-04-15 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0002_auto_20180415_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territory',
            options={'verbose_name_plural': 'territories'},
        ),
    ]
