# Generated by Django 2.0.4 on 2018-04-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0004_auto_20180421_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters',
                                    to='employee.Parameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments',
                                    to='employee.Department'),
        ),
    ]
