# Generated by Django 2.0.4 on 2018-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0005_auto_20180421_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
