# Generated by Django 2.0.4 on 2018-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0007_parameter_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nik',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(choices=[('not-assestment', 'Belum Dinilai'), ('productive', 'Produktif'),
                                            ('not-productive', 'Tidak Produktif'), ('promoted', 'Promosi'),
                                            ('not-promoted', 'Tidak Promosi')], default='not-assestment',
                                   max_length=100),
        ),
    ]
