# Generated by Django 2.0.4 on 2018-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0008_auto_20180727_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(choices=[('not-assestment', 'Belum Dinilai'), ('productive', 'Produktif'),
                                            ('not-productive', 'Tidak Produktif')], default='not-assestment',
                                   max_length=100),
        ),
    ]
